### ISSUE TITLE
FigResponseCookies::forget?

### ISSUE THREAD

**Issue by undercloud** [dflydev/dflydev-fig-cookies#14]
FigResponseCookies::forget - method does not exists! Are you mean `FigResponseCookies::expire?

**Comment by harikt** [comment]
Good catch. The code addition was https://github.com/dflydev/dflydev-fig-cookies/pull/10  and docs for https://github.com/dflydev/dflydev-fig-cookies/pull/11 . So yes expire. 

Ping @franzliedke

**Comment by harikt** [comment]
and related https://github.com/dflydev/dflydev-fig-cookies/issues/12 .

**Comment by harikt** [comment]
Fixed in https://github.com/dflydev/dflydev-fig-cookies/pull/15 .

**Comment by undercloud** [comment]
Your lib is awesome!

**Comment by franzliedke** [comment]
@undercloud @harikt Thanks for discovering and fixing this, and sorry about the mishap.

**Comment by harikt** [comment]
@franzliedke no issues. Was just making sure it was expire than forget then only found the other issue mentioning easypick in docs. So I did send the PR. Sorry to bother you.
