### ISSUE TITLE
Can SetCookie's constructor take more arguments?

### ISSUE THREAD

**Issue by rlanvin** [dflydev/dflydev-fig-cookies#26]
As far as I understand, `SetCookie::__construct` only takes `name` and `value`. If I want to create a cookie with expire, domain, path, etc. I have to chain a bunch of `->withDomain`, `->withPath`, and so on. 

Would it make sense to have `SetCookie` accept everything (domain, path, expires, etc.) in the constructor as optional arguments, much like PHP's native `setcookie` method? It would make instantiation much less verbose, and also avoid cloning and throwing away objects.

If it makes sense I can work on a PR for this.

**Comment by franzliedke** [comment]
The API of `setcookie()` isn't exactly beautiful. 😅 With named arguments in PHP 8, it might be more manageable...

**Comment by rlanvin** [comment]
Hey guys, I opened this issue in 2017... I have no idea why this issue got so much attention all of the sudden, but it's cool to see this project alive, I guess? :-) 

> My understanding is that this is not expensive at all.

You're probably correct, but "not expensive" doesn't mean it's free either. I do not remember the use case we had back then though, so not going to argue this is something you should be concerned about.

Anyway, feel free to close the ticket, it's obviously not relevant to me any more. Good luck with the package!

Cheers
