### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by canvural** [dflydev/dflydev-fig-cookies#38]
Hello,

One of the libraries I depend on has a dependency on this package. So while trying to upgrade to PHP8 I saw this package is not compatible.

Is there any plan to add support for PHP 8? If not, I can do it. Would you be interested merging that?

As far as I see it's relatively easy upgrade. Only problem I see is tests using `prophesize` which is deprecated in PHPUnit 9. https://github.com/phpspec/prophecy-phpunit is recommended but that requires min. PHP 7.3 So I don't know any what to do in that case, but open to discussion.

**Comment by simensen** [comment]
@canvural Indeed, I dropped the ball on this one. :( Someone opened #39 to try to properly support PHP 8 and I'm going to see if I can get some help following up on it and getting it merged ASAP if it's all good.

**Comment by canvural** [comment]
Yeah that's also my PR :smile:

**Comment by simensen** [comment]
@canvural D'oh. My bad for not noticing. Thank you so much for working on this for me! If we get the PR merged we'll get this issue closed. :)

**Comment by Venorcis** [comment]
Hello, is there any ETA on the availabillity of a PHP8-supported version?

**Comment by simensen** [comment]
This should be fixed, now. Thanks for your help!
